apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: folder4study
  labels:
    app: postgres
    version: latest
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
