kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: folder4study
  labels:
    app: postgres
    version: latest
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi