apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: folder4study
  labels:
    app: postgres
    version: latest
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - name: port
      port: 5432
      targetPort: port